  CREATE TABLE "CBGRAD" 
   (	"CODGRAD" VARCHAR2(10), 
	"DENUMIRE" VARCHAR2(50), 
	"TARIF" NUMBER, 
	 PRIMARY KEY ("CODGRAD")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CBMEDIC" 
   (	"MEDID" VARCHAR2(10), 
	"NUME" VARCHAR2(50), 
	"CODSPEC" VARCHAR2(10), 
	"CODGRAD" VARCHAR2(10), 
	 PRIMARY KEY ("MEDID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CBPROGRAMARE" 
   (	"CODPRO" VARCHAR2(10), 
	"DATA" DATE, 
	"CNP" VARCHAR2(13), 
	"NUME" VARCHAR2(50), 
	"MEDID" VARCHAR2(10), 
	"CABINET" VARCHAR2(10), 
	 PRIMARY KEY ("CODPRO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CBRETETA" 
   (	"CODPRO" VARCHAR2(10), 
	"NRITEM" NUMBER, 
	"MEDICAMENT" VARCHAR2(50), 
	"DOZA_ZI" VARCHAR2(20), 
	"DURATA_ZILE" NUMBER, 
	 CONSTRAINT "PK_RETETA" PRIMARY KEY ("CODPRO", "NRITEM")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CBSPECIALITATE" 
   (	"CODSPEC" VARCHAR2(10), 
	"DENUMIRE" VARCHAR2(50), 
	"COEFPLATA" NUMBER(5,2), 
	 PRIMARY KEY ("CODSPEC")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "CBMEDIC" ADD CONSTRAINT "FK_MEDIC_GRAD" FOREIGN KEY ("CODGRAD")
	  REFERENCES "CBGRAD" ("CODGRAD") ENABLE;
  ALTER TABLE "CBMEDIC" ADD CONSTRAINT "FK_MEDIC_SPEC" FOREIGN KEY ("CODSPEC")
	  REFERENCES "CBSPECIALITATE" ("CODSPEC") ENABLE;

  ALTER TABLE "CBPROGRAMARE" ADD CONSTRAINT "FK_PROG_MEDIC" FOREIGN KEY ("MEDID")
	  REFERENCES "CBMEDIC" ("MEDID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "CBPROGRAMARE_TRG" 
BEFORE INSERT ON cbprogramare
FOR EACH ROW
BEGIN
  IF :NEW.codpro IS NULL THEN
    SELECT 'P' || cbprogramare_seq.NEXTVAL
    INTO :NEW.codpro
    FROM dual;
  END IF;
END;
/
ALTER TRIGGER "CBPROGRAMARE_TRG" ENABLE;

  ALTER TABLE "CBRETETA" ADD CONSTRAINT "FK_RETETA_PROG" FOREIGN KEY ("CODPRO")
	  REFERENCES "CBPROGRAMARE" ("CODPRO") ENABLE;

   CREATE SEQUENCE  "CBPROGRAMARE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7339 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;